---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policyreport
spec:
  replicas: 3
  selector:
    matchLabels:
      name: policyreport
  template:
    metadata:
      labels:
        name: policyreport
    spec:
      containers:
      - name: policyreport
        image: mritunjay394/policyreport
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"